#!/usr/bin/env bash
set -euo pipefail
ROOT="$1"
PASS=0
FAIL=0
check(){ local name="$1"; shift; if "$@"; then echo "PASS $name"; PASS=$((PASS+1)); else echo "FAIL $name"; FAIL=$((FAIL+1)); fi; }
BG="$ROOT/app/build.gradle.kts"
MAN="$ROOT/app/src/main/AndroidManifest.xml"
MAIN="$ROOT/app/src/main/java/nexus/android/c002/MainActivity.kt"
CHAT="$ROOT/app/src/main/assets/nexus/chatgpt_provider_c002.js"
ORIGIN="$ROOT/app/src/main/java/nexus/android/c002/web/OriginPolicy.kt"
BRIDGE="$ROOT/app/src/main/java/nexus/android/c002/web/NexusWebBridge.kt"
check app_id grep -Fq 'applicationId = "nexus.android.v007.cleandevicee2e001.authfix2"' "$BG"
check version grep -Fq 'versionName = "0.0.32-v007-clean-device-e2e001-authfix2"' "$BG"
check label grep -Fq 'android:label="NEXUS V007 CLEAN DEVICE AUTHFIX2"' "$MAN"
check unique_profile grep -Fq 'nexus_provider_profile_v007_clean_device_e2e_001_authfix2' "$MAIN"
check authfix2_job grep -Fq 'V007-CLEAN-DEVICE-E2E-001-AUTHFIX2-JOB-001' "$MAIN"
check authfix2_pack grep -Fq 'V007_ANDROID_CLEAN_DEVICE_E2E_001_AUTHFIX2_V1' "$MAIN"
check authfix2_token grep -Fq 'NEXUS_V007_CLEAN_DEVICE_E2E_001_AUTHFIX2_OK' "$MAIN"
check chatgpt_selected grep -Fq 'provider = SelectedProvider.CHATGPT' "$MAIN"
check external_research_false grep -Fq '.put("external_research", false)' "$MAIN"
check canonical_write_false grep -Fq '.put("canonical_write", false)' "$MAIN"
check state_mutation_none grep -Fq '.put("state_mutation_mode", "NONE")' "$MAIN"
check truth_winner_none grep -Fq '.put("truth_winner", "NONE")' "$MAIN"
check terminal_receipt grep -Fq 'TERMINAL_RECEIPT_PASS' "$MAIN"
check authoritative_profile_marker grep -Fq 'data-testid="accounts-profile-button"' "$CHAT"
check current_unauth_not_retained grep -Fq "lastStableAuthState==='AUTHENTICATED'" "$CHAT"
check auto_probe_mode grep -Fq "mode:'AUTO_AUTH_MENU_PROBE'" "$CHAT"
check menu_not_auth_proof grep -Fq 'MENU_CLICK_IS_NOT_AUTH_PROOF' "$CHAT"
check menu_click_false_meta grep -Fq 'menu_click_is_auth_proof:false' "$CHAT"
check unique_menu_gate grep -Fq 'matches.length===1?matches[0]:null' "$CHAT"
check open_sidebar_testid grep -Fq 'open-sidebar-button' "$CHAT"
check french_sidebar_label grep -Fq 'Ouvrir la barre latérale' "$CHAT"
check unknown_stability grep -Fq 'Date.now()-authProbeUnknownSince<2500' "$CHAT"
check one_probe_gate grep -Fq 'if(authProbeAttempted) return;' "$CHAT"
check current_unauth_resets_probe grep -Fq "authProbeLast='CURRENT_UNAUTH_EVIDENCE'" "$CHAT"
check no_execution_from_probe bash -c "! sed -n '/function maybeAutoOpenAuthMenu/,/^  }/p' '$CHAT' | grep -Fq 'executeJob'"
check exact_chatgpt_origin grep -Fq 'const val CHATGPT_ORIGIN = "https://chatgpt.com"' "$MAIN"
check auth_google_exact grep -Fq 'host == "accounts.google.com"' "$ORIGIN"
check no_webview_debug bash -c "! grep -Fq 'setWebContentsDebuggingEnabled(true)' '$MAIN'"
check node_syntax node --check "$CHAT"
check bridge_exists test -s "$BRIDGE"
echo "V007_AUTHFIX2_STATIC_RESULT pass=$PASS fail=$FAIL"
test "$FAIL" -eq 0
