#!/usr/bin/env bash
set -euo pipefail
ROOT="$1"
PASS=0
FAIL=0
check(){ local name="$1"; shift; if "$@"; then echo "PASS $name"; PASS=$((PASS+1)); else echo "FAIL $name"; FAIL=$((FAIL+1)); fi; }
BG="$ROOT/app/build.gradle.kts"
MAN="$ROOT/app/src/main/AndroidManifest.xml"
MAIN="$ROOT/app/src/main/java/nexus/android/c002/MainActivity.kt"
CHAT="$ROOT/app/src/main/assets/nexus/chatgpt_provider_c002.js"
ORIGIN="$ROOT/app/src/main/java/nexus/android/c002/web/OriginPolicy.kt"
BRIDGE="$ROOT/app/src/main/java/nexus/android/c002/web/NexusWebBridge.kt"
check app_id grep -Fq 'applicationId = "nexus.android.v007.cleandevicee2e001.authfix1"' "$BG"
check version grep -Fq 'versionName = "0.0.31-v007-clean-device-e2e001-authfix1"' "$BG"
check label grep -Fq 'android:label="NEXUS V007 CLEAN DEVICE AUTHFIX1"' "$MAN"
check unique_profile grep -Fq 'nexus_provider_profile_v007_clean_device_e2e_001_authfix1' "$MAIN"
check old_profile_absent bash -c "! grep -Fq 'const val PROFILE_NAME = \"nexus_provider_profile_v007_clean_device_e2e_001\"' '$MAIN'"
check authfix_job grep -Fq 'V007-CLEAN-DEVICE-E2E-001-AUTHFIX1-JOB-001' "$MAIN"
check authfix_pack grep -Fq 'V007_ANDROID_CLEAN_DEVICE_E2E_001_AUTHFIX1_V1' "$MAIN"
check authfix_token grep -Fq 'NEXUS_V007_CLEAN_DEVICE_E2E_001_AUTHFIX1_OK' "$MAIN"
check chatgpt_selected grep -Fq 'provider = SelectedProvider.CHATGPT' "$MAIN"
check external_research_false grep -Fq '.put("external_research", false)' "$MAIN"
check canonical_write_false grep -Fq '.put("canonical_write", false)' "$MAIN"
check state_mutation_none grep -Fq '.put("state_mutation_mode", "NONE")' "$MAIN"
check truth_winner_none grep -Fq '.put("truth_winner", "NONE")' "$MAIN"
check terminal_receipt grep -Fq 'TERMINAL_RECEIPT_PASS' "$MAIN"
check profile_marker_unfiltered grep -Fq 'const profileMarkers=[...document.querySelectorAll('\''[data-testid="accounts-profile-button"]'\'')];' "$CHAT"
check visible_profile_separate grep -Fq 'const visibleProfiles=profileMarkers.filter(visible);' "$CHAT"
check auth_controls_extended grep -Fq 'document.querySelectorAll('\''button,a,[role="button"]'\'')' "$CHAT"
check collapsed_auth_reason grep -Fq 'RUNTIME_PROVEN_COLLAPSED_PROFILE_MARKER_PRESENT_AND_LOGIN_SIGNUP_ABSENT' "$CHAT"
check marker_positive_gate grep -Fq 'if(profileMarkers.length>0 && neg.length===0)' "$CHAT"
check marker_negative_gate grep -Fq 'else if(profileMarkers.length===0 && neg.length>0)' "$CHAT"
check no_composer_auth_heuristic bash -c "! sed -n '/function detectAuth(){/,/^  }/p' '$CHAT' | grep -Fq 'findComposer'"
check exact_chatgpt_origin grep -Fq 'const val CHATGPT_ORIGIN = "https://chatgpt.com"' "$MAIN"
check auth_google_exact grep -Fq 'host == "accounts.google.com"' "$ORIGIN"
check no_webview_debug bash -c "! grep -Fq 'setWebContentsDebuggingEnabled(true)' '$MAIN'"
check node_syntax node --check "$CHAT"
check bridge_exists test -s "$BRIDGE"
echo "V007_AUTHFIX1_STATIC_RESULT pass=$PASS fail=$FAIL"
test "$FAIL" -eq 0
