from pathlib import Path
import subprocess,sys
repo=Path(sys.argv[1]).resolve(); work=Path(sys.argv[2]).resolve()
subprocess.run([sys.executable,str(repo/'u004ux004'/'derive.py'),str(repo),str(work)],check=True)

p=work/'app/build.gradle.kts'; s=p.read_text(); s=s.replace('applicationId = "nexus.android.u004.uxshell004"','applicationId = "nexus.android.u013.i18n001"').replace('versionCode = 43','versionCode = 44').replace('versionName = "0.0.43-u004-android-ux-shell004-content"','versionName = "0.0.44-u013-i18n-shared001"'); assert 'nexus.android.u013.i18n001' in s; p.write_text(s)
res=work/'app/src/main/res'
for d in ('values','values-en','values-de'):(res/d).mkdir(parents=True,exist_ok=True)
texts={
'values':{'menu_nexus':'Menu NEXUS','status_connecting':'Connexion au fournisseur…','status_auth_required':'Connexion à ChatGPT requise','status_connected':'Connecté · préparation de NEXUS','status_request_sent':'Requête envoyée · analyse en cours','status_complete':'Terminé · résultat validé','status_running':'Analyse en cours…','status_blocked':'Exécution bloquée · vérification de sécurité','technical_details':'Détails techniques','hide_technical_details':'Masquer les détails techniques','show_provider_response':'Voir la réponse ChatGPT','show_nexus_result':'Afficher le résultat NEXUS','result_title':'Résultat NEXUS','result_waiting':'Contenu du résultat en attente…','result_empty':'Résultat validé, contenu vide.','result_validated_suffix':'Validé par NEXUS · ChatGPT','result_footer':'La réponse fournisseur et les détails techniques restent accessibles depuis le menu ⋮.','language':'Langue de l’interface','language_auto':'Auto','language_fr':'Français','language_en':'English','language_de':'Deutsch'},
'values-en':{'menu_nexus':'NEXUS menu','status_connecting':'Connecting to provider…','status_auth_required':'ChatGPT sign-in required','status_connected':'Connected · preparing NEXUS','status_request_sent':'Request sent · analysis in progress','status_complete':'Complete · result validated','status_running':'Analysis in progress…','status_blocked':'Execution blocked · security check','technical_details':'Technical details','hide_technical_details':'Hide technical details','show_provider_response':'View ChatGPT response','show_nexus_result':'Show NEXUS result','result_title':'NEXUS result','result_waiting':'Waiting for result content…','result_empty':'Validated result, empty content.','result_validated_suffix':'Validated by NEXUS · ChatGPT','result_footer':'The provider response and technical details remain available from the ⋮ menu.','language':'Interface language','language_auto':'Auto','language_fr':'Français','language_en':'English','language_de':'Deutsch'},
'values-de':{'menu_nexus':'NEXUS-Menü','status_connecting':'Verbindung zum Anbieter wird hergestellt…','status_auth_required':'ChatGPT-Anmeldung erforderlich','status_connected':'Verbunden · NEXUS wird vorbereitet','status_request_sent':'Anfrage gesendet · Analyse läuft','status_complete':'Abgeschlossen · Ergebnis validiert','status_running':'Analyse läuft…','status_blocked':'Ausführung blockiert · Sicherheitsprüfung','technical_details':'Technische Details','hide_technical_details':'Technische Details ausblenden','show_provider_response':'ChatGPT-Antwort anzeigen','show_nexus_result':'NEXUS-Ergebnis anzeigen','result_title':'NEXUS-Ergebnis','result_waiting':'Warten auf Ergebnisinhalt…','result_empty':'Validiertes Ergebnis, leerer Inhalt.','result_validated_suffix':'Von NEXUS validiert · ChatGPT','result_footer':'Die Anbieterantwort und technischen Details bleiben über das Menü ⋮ verfügbar.','language':'Oberflächensprache','language_auto':'Auto','language_fr':'Français','language_en':'English','language_de':'Deutsch'}}
for d,m in texts.items():
    body=['<?xml version="1.0" encoding="utf-8"?>','<resources>','    <string name="app_name">NEXUS</string>']+[f'    <string name="{k}">{v}</string>' for k,v in m.items()]+['</resources>']
    (res/d/'strings.xml').write_text('\n'.join(body)+'\n')

p=res/'layout/activity_main.xml'; s=p.read_text();
for a,b in {'android:contentDescription="Menu NEXUS"':'android:contentDescription="@string/menu_nexus"','android:text="Connexion au fournisseur…"':'android:text="@string/status_connecting"','android:text="Résultat NEXUS"':'android:text="@string/result_title"','android:text="Contenu du résultat en attente…"':'android:text="@string/result_waiting"','android:text="La réponse fournisseur et les détails techniques restent accessibles depuis le menu ⋮."':'android:text="@string/result_footer"'}.items():s=s.replace(a,b)
p.write_text(s)

p=work/'app/src/main/java/nexus/android/c002/MainActivity.kt'; s=p.read_text(); s=s.replace('import android.os.Bundle\n','import android.os.Bundle\nimport android.content.Context\nimport android.content.res.Configuration\nimport java.util.Locale\n')
anchor='class MainActivity : Activity() {\n'; assert anchor in s
locale='''class MainActivity : Activity() {\n    override fun attachBaseContext(newBase: Context) {\n        val pref=newBase.getSharedPreferences("nexus_ui",Context.MODE_PRIVATE).getString("language","auto")?:"auto"\n        val system=Locale.getDefault().language.lowercase(Locale.ROOT)\n        val tag=if(pref=="auto") { if(system in setOf("fr","en","de")) system else "fr" } else pref\n        val config=Configuration(newBase.resources.configuration); config.setLocale(Locale.forLanguageTag(tag))\n        super.attachBaseContext(newBase.createConfigurationContext(config))\n    }\n    private fun setUiLanguage(tag:String){ getSharedPreferences("nexus_ui",Context.MODE_PRIVATE).edit().putString("language",tag).apply(); recreate() }\n\n'''
s=s.replace(anchor,locale,1)
old='''    private fun friendlyHeadline(raw: String): String = when {\n        raw.startsWith("AUTH REQUIRED") -> "Connexion à ChatGPT requise"\n        raw.startsWith("DESCRIBE PASS") -> "Connecté · préparation de NEXUS"\n        raw.startsWith("ACK PASS") -> "Requête envoyée · analyse en cours"\n        raw.startsWith("EXECUTION PROOF PASS") -> "Terminé · résultat validé"\n        raw.startsWith("EXECUTION PROOF") -> "Analyse en cours…"\n        raw.startsWith("BLOCKED") -> "Exécution bloquée · vérification de sécurité"\n        raw.startsWith("U004 UX") -> "Connexion au fournisseur…"\n        else -> raw\n    }\n'''
new='''    private fun friendlyHeadline(raw: String): String = when {\n        raw.startsWith("AUTH REQUIRED") -> getString(R.string.status_auth_required)\n        raw.startsWith("DESCRIBE PASS") -> getString(R.string.status_connected)\n        raw.startsWith("ACK PASS") -> getString(R.string.status_request_sent)\n        raw.startsWith("EXECUTION PROOF PASS") -> getString(R.string.status_complete)\n        raw.startsWith("EXECUTION PROOF") -> getString(R.string.status_running)\n        raw.startsWith("BLOCKED") -> getString(R.string.status_blocked)\n        raw.startsWith("U004 UX") -> getString(R.string.status_connecting)\n        else -> raw\n    }\n'''; assert old in s; s=s.replace(old,new)
start=s.index('        val menuButton: Button = findViewById(R.id.nexusMenu)\n'); end=s.index('            popup.show()\n        }\n',start)+len('            popup.show()\n        }\n')
menu='''        val menuButton: Button = findViewById(R.id.nexusMenu)\n        menuButton.setOnClickListener { anchorView ->\n            val popup=PopupMenu(this,anchorView)\n            popup.menu.add(0,100,0,if(diagnosticExpanded)getString(R.string.hide_technical_details) else getString(R.string.technical_details))\n            if(proofStopped) popup.menu.add(0,101,1,if(resultPanel.visibility==View.VISIBLE)getString(R.string.show_provider_response) else getString(R.string.show_nexus_result))\n            val lm=popup.menu.addSubMenu(getString(R.string.language)); lm.add(0,200,0,getString(R.string.language_auto)); lm.add(0,201,1,getString(R.string.language_fr)); lm.add(0,202,2,getString(R.string.language_en)); lm.add(0,203,3,getString(R.string.language_de))\n            popup.setOnMenuItemClickListener { item -> when(item.itemId){100->{diagnosticExpanded=!diagnosticExpanded;renderStatus()};101->if(resultPanel.visibility==View.VISIBLE)showProviderResponse() else showNexusResult();200->setUiLanguage("auto");201->setUiLanguage("fr");202->setUiLanguage("en");203->setUiLanguage("de")}; true }\n            popup.show()\n        }\n'''; s=s[:start]+menu+s[end:]
s=s.replace('append(userAnswer.ifBlank { "Résultat validé, contenu vide." })','append(userAnswer.ifBlank { getString(R.string.result_empty) })').replace('append("\\n\\nValidé par NEXUS · ChatGPT")','append("\\n\\n").append(getString(R.string.result_validated_suffix))')
p.write_text(s)
print('U013-I18N-SHARED-001 ready')
