#!/usr/bin/env bash
set -euo pipefail
ROOT="${1:?root required}"
REF="${2:?021 reference required}"
pass=0; fail=0
check(){ local n="$1"; shift; if "$@"; then echo "PASS $n"; pass=$((pass+1)); else echo "FAIL $n"; fail=$((fail+1)); fi; }
MAIN="$ROOT/app/src/main/java/nexus/android/c002/MainActivity.kt"
GRADLE="$ROOT/app/build.gradle.kts"
MANIFEST="$ROOT/app/src/main/AndroidManifest.xml"
CLAUDE="$ROOT/app/src/main/assets/nexus/claude_provider_c002.js"
CHATGPT="$ROOT/app/src/main/assets/nexus/chatgpt_provider_c002.js"
ORIGIN="$ROOT/app/src/main/java/nexus/android/c002/web/OriginPolicy.kt"
BRIDGE="$ROOT/app/src/main/java/nexus/android/c002/web/NexusWebBridge.kt"
check application_id_stable grep -Fq 'applicationId = "nexus.android.c002.providerrunresume021"' "$GRADLE"
check version_022 grep -Fq 'versionCode = 23' "$GRADLE"
check version_name_022 grep -Fq '0.0.23-c002-provider-run-resume-diagnostic022' "$GRADLE"
check label_022 grep -Fq 'NEXUS C002 RUN RESUME DIAGNOSTIC 022' "$MANIFEST"
check stable_webview_profile grep -Fq 'nexus_provider_profile_c002_rotationrunstate019' "$MAIN"
check recoverable_banner grep -Fq 'RECOVERABLE — CLOSE AND REOPEN NEXUS NOW' "$MAIN"
check recoverable_event grep -Fq 'RUN_RECOVERABLE_WINDOW' "$MAIN"
check resume_pending_banner grep -Fq 'RUN RESUME PENDING 022 — SAME RUN / NO RESUBMIT' "$MAIN"
check resume_observer_banner grep -Fq 'RUN RESUME 022 — OBSERVER ONLY / SAME CLAUDE CONVERSATION' "$MAIN"
check resume_event grep -Fq 'RESUME_JOB_022' "$MAIN"
check no_resubmit_telemetry grep -Fq 'prompt_injection=false;send_click=false' "$MAIN"
check resume_job_preserved grep -Fq 'put("type", "RESUME_JOB")' "$MAIN"
check resume_adapter_preserved grep -Fq 'async function resumeJob' "$CLAUDE"
check resume_observer_preserved grep -Fq 'CLAUDE_RESUME_OBSERVER_STARTED' "$CLAUDE"
check submission_proof020_preserved grep -Fq 'CLAUDE_SUBMISSION_ESTABLISHED__' "$CLAUDE"
check rotation_preserved grep -Fq 'CONFIGURATION_CHANGED' "$MAIN"
check chatgpt_identical cmp -s "$CHATGPT" "$REF/app/src/main/assets/nexus/chatgpt_provider_c002.js"
check origin_identical cmp -s "$ORIGIN" "$REF/app/src/main/java/nexus/android/c002/web/OriginPolicy.kt"
check bridge_identical cmp -s "$BRIDGE" "$REF/app/src/main/java/nexus/android/c002/web/NexusWebBridge.kt"
check claude_identical cmp -s "$CLAUDE" "$REF/app/src/main/assets/nexus/claude_provider_c002.js"
check no_prompt_persisted bash -c "! grep -q 'RUN_LATCH_QUESTION\|PROOF_QUESTION.*putString\|PROOF_HANDOFF.*putString' '$MAIN'"
check no_cookie_persisted bash -c "! grep -qi 'putString.*cookie' '$MAIN'"
check claude_js_syntax node --check "$CLAUDE"
echo "PROVIDER_RUN_RESUME_DIAGNOSTIC_022_STATIC_RESULT pass=$pass fail=$fail"
test "$fail" -eq 0
