#!/usr/bin/env bash
set -euo pipefail
ROOT="$1"
PASS=0
FAIL=0
check(){ local name="$1"; shift; if "$@"; then echo "PASS $name"; PASS=$((PASS+1)); else echo "FAIL $name"; FAIL=$((FAIL+1)); fi; }
BG="$ROOT/app/build.gradle.kts"
MAN="$ROOT/app/src/main/AndroidManifest.xml"
MAIN="$ROOT/app/src/main/java/nexus/android/c002/MainActivity.kt"
LAY="$ROOT/app/src/main/res/layout/activity_main.xml"
CHAT="$ROOT/app/src/main/assets/nexus/chatgpt_provider_c002.js"
ORIGIN="$ROOT/app/src/main/java/nexus/android/c002/web/OriginPolicy.kt"
BRIDGE="$ROOT/app/src/main/java/nexus/android/c002/web/NexusWebBridge.kt"

check app_id grep -Fq 'applicationId = "nexus.android.u004.uxshell003"' "$BG"
check version grep -Fq 'versionName = "0.0.42-u004-android-ux-shell003-user-result"' "$BG"
check label grep -Fq 'android:label="NEXUS"' "$MAN"
check unique_profile grep -Fq 'nexus_provider_profile_u004_android_ux_shell_003' "$MAIN"
check u004_job grep -Fq 'U004-ANDROID-UX-SHELL-003-JOB-001' "$MAIN"
check u004_pack grep -Fq 'U004_ANDROID_UX_SHELL_003_V1' "$MAIN"
check u004_token grep -Fq 'NEXUS_U004_ANDROID_UX_SHELL_003_OK' "$MAIN"
check nexus_title grep -Fq 'android:text="NEXUS"' "$LAY"
check provider_visible grep -Fq 'android:text="ChatGPT"' "$LAY"
check friendly_pass grep -Fq 'Terminé · résultat validé' "$MAIN"
check result_panel grep -Fq 'android:id="@+id/resultPanel"' "$LAY"
check result_summary grep -Fq 'android:id="@+id/resultSummary"' "$LAY"
check result_title grep -Fq 'android:text="Résultat NEXUS"' "$LAY"
check user_summary grep -Fq 'La réponse du fournisseur a été reçue et validée par NEXUS.' "$MAIN"
check user_status grep -Fq 'Statut : Validé' "$MAIN"
check hide_webview grep -Fq 'webView.visibility = View.GONE' "$MAIN"
check show_result grep -Fq 'resultPanel.visibility = View.VISIBLE' "$MAIN"
check provider_on_demand grep -Fq 'Voir la réponse ChatGPT' "$MAIN"
check result_return grep -Fq 'Afficher le résultat NEXUS' "$MAIN"
check provider_toggle grep -Fq 'private fun showProviderResponse()' "$MAIN"
check nexus_toggle grep -Fq 'private fun showNexusResult()' "$MAIN"
check raw_details_on_demand bash -c "grep -Fq 'diagnosticExpanded' '$MAIN' && grep -Fq 'currentBody' '$MAIN' && grep -Fq 'Détails techniques' '$MAIN'"
check diagnostic_badge_hidden grep -Fq "'display:none','position:fixed'" "$CHAT"
check authfix2_probe grep -Fq "mode:'AUTO_AUTH_MENU_PROBE'" "$CHAT"
check autoclose_function grep -Fq 'function findAuthMenuCloseButton()' "$CHAT"
check autoclose_only_nexus_opened grep -Fq 'if(!authProbeOpenedSidebar) return;' "$CHAT"
check autoclose_not_auth_proof grep -Fq 'sidebar_close_is_auth_proof:false' "$CHAT"
check menu_click_not_auth_proof grep -Fq 'menu_click_is_auth_proof:false' "$CHAT"
check exact_chatgpt_origin grep -Fq 'const val CHATGPT_ORIGIN = "https://chatgpt.com"' "$MAIN"
check auth_google_exact grep -Fq 'host == "accounts.google.com"' "$ORIGIN"
check terminal_receipt grep -Fq 'TERMINAL_RECEIPT_PASS' "$MAIN"
check external_research_false grep -Fq '.put("external_research", false)' "$MAIN"
check canonical_write_false grep -Fq '.put("canonical_write", false)' "$MAIN"
check state_mutation_none grep -Fq '.put("state_mutation_mode", "NONE")' "$MAIN"
check truth_winner_none grep -Fq '.put("truth_winner", "NONE")' "$MAIN"
check no_webview_debug bash -c "! grep -Fq 'setWebContentsDebuggingEnabled(true)' '$MAIN'"
check node_syntax node --check "$CHAT"
check no_add_javascript_interface_main bash -c "! grep -Fq 'addJavascriptInterface' '$MAIN'"
check no_add_javascript_interface_bridge bash -c "! grep -Fq 'addJavascriptInterface' '$BRIDGE'"

echo "U004_UX_SHELL_003_STATIC_RESULT pass=$PASS fail=$FAIL"
test "$FAIL" -eq 0
