from pathlib import Path
import re, subprocess, sys
repo=Path(sys.argv[1]).resolve(); root=Path(sys.argv[2]).resolve()
subprocess.run(['python3',str(repo/'claudesubmissionproof020'/'derive.py'),str(repo),str(root)],check=True)

# identity only; keep the 019 WebView profile stable so provider auth/session storage is not rotated again.
p=root/'app/build.gradle.kts'; g=p.read_text()
g=g.replace('applicationId = "nexus.android.c002.claudesubmissionproof020"','applicationId = "nexus.android.c002.providerrunresume021"').replace('versionCode = 21','versionCode = 22')
g,n=re.subn(r'versionName\s*=\s*"0\.0\.21-c002-[^"]+"','versionName = "0.0.22-c002-provider-run-resume021"',g,count=1); assert n==1
p.write_text(g)
p=root/'app/src/main/AndroidManifest.xml'; m=p.read_text(); assert m.count('android:label="NEXUS C002 CLAUDE SUBMISSION PROOF 020"')==1
p.write_text(m.replace('android:label="NEXUS C002 CLAUDE SUBMISSION PROOF 020"','android:label="NEXUS C002 PROVIDER RUN RESUME 021"'))

main=root/'app/src/main/java/nexus/android/c002/MainActivity.kt'; s=main.read_text()
# Run-resume state is metadata-only: no prompt/frozen payload/cookie/secret is persisted.
old='''    private lateinit var runLatch: SharedPreferences\n    private var runLatchArmed = false\n'''
new='''    private lateinit var runLatch: SharedPreferences\n    private var runLatchArmed = false\n    private var resumePending = false\n    private var resumeAttempt = 0\n'''
assert s.count(old)==1; s=s.replace(old,new)

old='''        val priorStartedAt = runLatch.getLong(RUN_LATCH_STARTED_AT_KEY, 0L)\n        val priorAge = System.currentTimeMillis() - priorStartedAt\n        if (priorState == RUN_STATE_IN_FLIGHT && priorAge in 0..RUN_LATCH_TTL_MS) {\n            proofStopped = true\n            currentHeadline = "BLOCKED — ANDROID_INFLIGHT_RUN_RECREATION_DETECTED"\n            currentBody = "A recent provider run is latched in-flight; duplicate auto-start is forbidden. age_ms=$priorAge"\n            runLatch.edit().putString(RUN_LATCH_STATE_KEY, RUN_STATE_RECREATION_BLOCKED).apply()\n            renderStatus()\n            return\n        }\n        runLatch.edit()\n            .putString(RUN_LATCH_STATE_KEY, RUN_STATE_IDLE)\n            .remove(RUN_LATCH_STARTED_AT_KEY)\n            .apply()\n'''
new='''        val priorStartedAt = runLatch.getLong(RUN_LATCH_STARTED_AT_KEY, 0L)\n        val priorLastSeenAt = runLatch.getLong(RUN_LATCH_LAST_SEEN_AT_KEY, priorStartedAt)\n        val priorAge = System.currentTimeMillis() - priorLastSeenAt\n        val resumable = priorState == RUN_STATE_IN_FLIGHT || priorState == RUN_STATE_RECOVERABLE\n        if (resumable && priorAge in 0..RUN_LATCH_TTL_MS) {\n            val persistedRunId = runLatch.getString(RUN_LATCH_BRIDGE_RUN_ID_KEY, null)\n            val persistedJobId = runLatch.getString(RUN_LATCH_JOB_ID_KEY, null)\n            val persistedProvider = runLatch.getString(RUN_LATCH_PROVIDER_KEY, null)\n            val persistedFingerprint = runLatch.getString(RUN_LATCH_FINGERPRINT_KEY, null)\n            resumeAttempt = runLatch.getInt(RUN_LATCH_RESUME_COUNT_KEY, 0)\n            if (persistedRunId != BRIDGE_RUN_ID || persistedJobId != JOB_ID || persistedProvider != "ANTHROPIC" || persistedFingerprint.isNullOrBlank()) {\n                proofStopped = true\n                currentHeadline = "BLOCKED — ANDROID_RUN_RESUME_METADATA_MISMATCH"\n                currentBody = "Persisted provider-run correlation metadata is incomplete or does not match this frozen proof build."\n                runLatch.edit().putString(RUN_LATCH_STATE_KEY, RUN_STATE_TERMINAL_BLOCKED).apply()\n                renderStatus(); return\n            }\n            if (resumeAttempt >= MAX_RESUME_ATTEMPTS) {\n                proofStopped = true\n                currentHeadline = "BLOCKED — ANDROID_RUN_RESUME_ATTEMPTS_EXHAUSTED"\n                currentBody = "Bounded resume attempts exhausted for the same provider run."\n                runLatch.edit().putString(RUN_LATCH_STATE_KEY, RUN_STATE_TERMINAL_BLOCKED).apply()\n                renderStatus(); return\n            }\n            resumePending = true\n            runLatchArmed = true\n            currentHeadline = "RUN RESUME PENDING — same provider run will be observed, not resubmitted"\n            currentBody = "state=$priorState;age_ms=$priorAge;resume_attempt=$resumeAttempt"\n        } else {\n            runLatch.edit().putString(RUN_LATCH_STATE_KEY, RUN_STATE_IDLE).remove(RUN_LATCH_STARTED_AT_KEY).remove(RUN_LATCH_LAST_SEEN_AT_KEY).apply()\n        }\n'''
assert s.count(old)==1; s=s.replace(old,new)

old='''        currentHeadline = "DESCRIBE PASS — stable Claude auth — execution proof starting"\n        currentBody = null\n        renderStatus()\n        startExecutionProof(origin)\n    }\n\n    private fun startExecutionProof(origin: String) {\n'''
new='''        currentHeadline = if (resumePending) "DESCRIBE PASS — stable Claude auth — resuming same provider run" else "DESCRIBE PASS — stable Claude auth — execution proof starting"\n        currentBody = null\n        renderStatus()\n        if (resumePending) resumeExecutionProof(origin) else startExecutionProof(origin)\n    }\n\n    private fun resumeExecutionProof(origin: String) {\n        if (!resumePending || !describePassed || executionStarted || proofStopped) return\n        val input = ExecutionInput(JOB_ID, PROOF_QUESTION, PROOF_HANDOFF, SelectedProvider.CLAUDE, null, false)\n        val job = runCatching { engine.buildJob(input) }.getOrElse { block("ANDROID_RESUME_JOB_REBUILD_FAILED"); return }\n        val persistedFingerprint = runLatch.getString(RUN_LATCH_FINGERPRINT_KEY, null)\n        if (persistedFingerprint != job.frozenFingerprint) { block("ANDROID_RUN_RESUME_FROZEN_FINGERPRINT_MISMATCH"); return }\n        proofJob = job\n        val channel = providerChannel ?: run { block("ANDROID_BRIDGE_CHANNEL_UNBOUND"); return }\n        val envelope = JSONObject()\n            .put("job_id", job.jobId)\n            .put("context_pack_id", job.contextPackId)\n            .put("frozen_fingerprint", job.frozenFingerprint)\n            .put("provider_family", job.providerFamily)\n            .put("external_research", false)\n            .put("canonical_rights", "NONE")\n            .put("state_mutation_mode", "NONE")\n        val outbound = JSONObject().put("channel", channel).put("type", "RESUME_JOB").put("bridge_run_id", BRIDGE_RUN_ID).put("envelope", envelope)\n        resumeAttempt += 1\n        runLatch.edit().putString(RUN_LATCH_STATE_KEY, RUN_STATE_IN_FLIGHT).putLong(RUN_LATCH_LAST_SEEN_AT_KEY, System.currentTimeMillis()).putInt(RUN_LATCH_RESUME_COUNT_KEY, resumeAttempt).putString(RUN_LATCH_PHASE_KEY, "RESUME_DISPATCH").apply()\n        resumePending = false; executionStarted = true\n        recordDiagnostic("RESUME_JOB", origin, "bridge_run_id=$BRIDGE_RUN_ID;resume_attempt=$resumeAttempt;resubmit=false")\n        currentHeadline = "RUN RESUME — observing existing Claude conversation"; currentBody = null; renderStatus()\n        if (bridge?.post(origin, outbound.toString()) != true) { block("ANDROID_RESUME_JOB_POST_FAILED"); return }\n        handler.postDelayed({ if (!ackPassed && !proofStopped) block("ANDROID_RESUME_ACK_TIMEOUT") }, ACK_TIMEOUT_MS)\n        handler.postDelayed({ if (!terminalReceived && !proofStopped) block("ANDROID_RESUME_TERMINAL_TIMEOUT") }, RESUME_TERMINAL_TIMEOUT_MS)\n    }\n\n    private fun startExecutionProof(origin: String) {\n'''
assert s.count(old)==1; s=s.replace(old,new)

# Persist correlation metadata when a fresh run is dispatched.
s=s.replace('armRunLatch()','armRunLatch(job)',1)
old='''    private fun armRunLatch() {\n        runLatchArmed = true\n        runLatch.edit()\n            .putString(RUN_LATCH_STATE_KEY, RUN_STATE_IN_FLIGHT)\n            .putLong(RUN_LATCH_STARTED_AT_KEY, System.currentTimeMillis())\n            .apply()\n    }\n'''
new='''    private fun armRunLatch(job: ExecutionJob) {\n        runLatchArmed = true\n        val now = System.currentTimeMillis()\n        runLatch.edit()\n            .putString(RUN_LATCH_STATE_KEY, RUN_STATE_IN_FLIGHT)\n            .putLong(RUN_LATCH_STARTED_AT_KEY, now)\n            .putLong(RUN_LATCH_LAST_SEEN_AT_KEY, now)\n            .putString(RUN_LATCH_BRIDGE_RUN_ID_KEY, BRIDGE_RUN_ID)\n            .putString(RUN_LATCH_JOB_ID_KEY, job.jobId)\n            .putString(RUN_LATCH_PROVIDER_KEY, "ANTHROPIC")\n            .putString(RUN_LATCH_FINGERPRINT_KEY, job.frozenFingerprint)\n            .putString(RUN_LATCH_PHASE_KEY, "EXECUTE_DISPATCH")\n            .putInt(RUN_LATCH_RESUME_COUNT_KEY, 0)\n            .apply()\n    }\n\n    private fun markRunProgress(phase: String) {\n        if (!::runLatch.isInitialized || !runLatchArmed) return\n        runLatch.edit().putLong(RUN_LATCH_LAST_SEEN_AT_KEY, System.currentTimeMillis()).putString(RUN_LATCH_PHASE_KEY, phase.take(160)).apply()\n    }\n\n    private fun markRunRecoverable(code: String) {\n        if (!::runLatch.isInitialized || !runLatchArmed) return\n        runLatch.edit().putString(RUN_LATCH_STATE_KEY, RUN_STATE_RECOVERABLE).putLong(RUN_LATCH_LAST_SEEN_AT_KEY, System.currentTimeMillis()).putString(RUN_LATCH_PHASE_KEY, "RECOVERABLE:" + sanitizeCode(code)).apply()\n    }\n\n    private fun isResumeEligibleBlock(code: String): Boolean =\n        code.startsWith("ANDROID_PROVIDER_FAILED:CLAUDE_PROMPT_SUBMISSION_NOT_ESTABLISHED") ||\n        code.startsWith("ANDROID_PROVIDER_FAILED:CLAUDE_USER_TURN_NOT_MATERIALIZED") ||\n        code.startsWith("ANDROID_PROVIDER_FAILED:CLAUDE_GENERATION_NOT_OBSERVED") ||\n        code.startsWith("ANDROID_PROVIDER_FAILED:CLAUDE_RESUME_") ||\n        code == "ANDROID_TERMINAL_TIMEOUT" || code == "ANDROID_RESUME_TERMINAL_TIMEOUT" || code == "ANDROID_RESUME_ACK_TIMEOUT" || code == "ANDROID_RESUME_JOB_POST_FAILED"\n'''
assert s.count(old)==1; s=s.replace(old,new)

# Refresh run ownership while provider activity is observed.
s=s.replace('''        ackPassed = true\n        recordDiagnostic("ACK_PASS", CLAUDE_ORIGIN, "bridge_run_id=$BRIDGE_RUN_ID")\n''','''        ackPassed = true\n        markRunProgress(if (resumeAttempt > 0) "RESUME_ACK_PASS" else "ACK_PASS")\n        recordDiagnostic("ACK_PASS", CLAUDE_ORIGIN, "bridge_run_id=$BRIDGE_RUN_ID;resume_attempt=$resumeAttempt")\n''',1)
s=s.replace('''        val jobStatus = message.optString("job_status", "UNKNOWN").take(96)\n        recordDiagnostic("PROVIDER_PROGRESS", CLAUDE_ORIGIN, "status=$jobStatus")\n''','''        val jobStatus = message.optString("job_status", "UNKNOWN").take(96)\n        markRunProgress(jobStatus)\n        recordDiagnostic("PROVIDER_PROGRESS", CLAUDE_ORIGIN, "status=$jobStatus")\n''',1)

old='''        if (::runLatch.isInitialized && runLatchArmed) closeRunLatch(RUN_STATE_TERMINAL_BLOCKED)\n        proofStopped = true\n'''
new='''        if (::runLatch.isInitialized && runLatchArmed) {\n            if (isResumeEligibleBlock(code) && resumeAttempt < MAX_RESUME_ATTEMPTS) markRunRecoverable(code) else closeRunLatch(RUN_STATE_TERMINAL_BLOCKED)\n        }\n        proofStopped = true\n'''
assert s.count(old)==1; s=s.replace(old,new)

s=s.replace('const val RUN_LATCH_PREFS = "nexus_v005_rotation_runstate_019"','const val RUN_LATCH_PREFS = "nexus_v005_provider_run_resume_021"')
s=s.replace('''        const val RUN_LATCH_STARTED_AT_KEY = "started_at_ms"\n''','''        const val RUN_LATCH_STARTED_AT_KEY = "started_at_ms"\n        const val RUN_LATCH_LAST_SEEN_AT_KEY = "last_seen_at_ms"\n        const val RUN_LATCH_BRIDGE_RUN_ID_KEY = "bridge_run_id"\n        const val RUN_LATCH_JOB_ID_KEY = "job_id"\n        const val RUN_LATCH_PROVIDER_KEY = "provider"\n        const val RUN_LATCH_FINGERPRINT_KEY = "frozen_fingerprint"\n        const val RUN_LATCH_PHASE_KEY = "phase"\n        const val RUN_LATCH_RESUME_COUNT_KEY = "resume_count"\n''')
s=s.replace('const val RUN_STATE_RECREATION_BLOCKED = "RECREATION_BLOCKED"','const val RUN_STATE_RECOVERABLE = "RECOVERABLE"')
s=s.replace('const val RUN_LATCH_TTL_MS = 300_000L','''const val RUN_LATCH_TTL_MS = 300_000L\n        const val MAX_RESUME_ATTEMPTS = 2\n        const val RESUME_TERMINAL_TIMEOUT_MS = 160_000L''')
main.write_text(s)

# Claude RESUME_JOB is observer-only: never writes to the composer and never clicks Send.
provider=root/'app/src/main/assets/nexus/claude_provider_c002.js'; j=provider.read_text()
anchor='''  async function executeJob(bridgeRunId,envelope){\n'''
resume='''  async function resumeJob(bridgeRunId,envelope){\n    if(running) throw new Error('CLAUDE_PROVIDER_ALREADY_RUNNING');\n    running=true;\n    try{\n      const auth=detectAuth();\n      if(auth.state!=='AUTHENTICATED') throw new Error('CLAUDE_NOT_AUTHENTICATED:'+auth.state);\n      if(envelope.provider_family!=='ANTHROPIC'||envelope.external_research!==false) throw new Error('CLAUDE_RESUME_ENVELOPE_INVALID');\n      await progress(bridgeRunId,'CLAUDE_RESUME_OBSERVER_STARTED');\n      await progress(bridgeRunId,'CLAUDE_RESUME_SNAPSHOT__'+compactTurnDiag(turnGenerationSnapshot(envelope)));\n      const result=await waitForStableJson(bridgeRunId,envelope,150000);\n      await progress(bridgeRunId,'CLAUDE_RESUME_RESPONSE_CAPTURED');\n      await nativeSend({channel:CHANNEL,type:'PROVIDER_RESULT',bridge_run_id:bridgeRunId,ok:true,result_pack:result.parsed,provider_meta:{ui_origin:location.origin,auth_observation:auth,exact_backend_model_exposed:false,completion_rule:'RESUME_EXISTING_CONVERSATION__COMPLETE_JSON_STABLE_8000MS',json_stable_ms:result.json_stable_ms,candidate_count:result.candidate_count,resumed:true}});\n    }catch(err){\n      const code=String(err?.message||err);\n      try{await nativeSend({channel:CHANNEL,type:'PROVIDER_RESULT',bridge_run_id:bridgeRunId,ok:false,error:'CLAUDE_RESUME_'+code});}catch(_){}\n    }finally{ running=false; setTimeout(publishStatus,2000); }\n  }\n\n  async function executeJob(bridgeRunId,envelope){\n'''
assert j.count(anchor)==1; j=j.replace(anchor,resume)
old='''    if(msg.type!=='EXECUTE_JOB') return;\n    if(running){\n      sendResponse({ok:false,error:'CLAUDE_PROVIDER_ALREADY_RUNNING'});\n      return;\n    }\n    sendResponse({ok:true,accepted:true});\n    setTimeout(()=>executeJob(msg.bridge_run_id,msg.envelope),0);\n    return;\n'''
new='''    if(msg.type!=='EXECUTE_JOB' && msg.type!=='RESUME_JOB') return;\n    if(running){ sendResponse({ok:false,error:'CLAUDE_PROVIDER_ALREADY_RUNNING'}); return; }\n    const resumed=msg.type==='RESUME_JOB';\n    sendResponse({ok:true,accepted:true,resumed});\n    setTimeout(()=>resumed?resumeJob(msg.bridge_run_id,msg.envelope):executeJob(msg.bridge_run_id,msg.envelope),0);\n    return;\n'''
assert j.count(old)==1; provider.write_text(j.replace(old,new))
