from pathlib import Path
import sys

path = Path(sys.argv[1])
s = path.read_text(encoding="utf-8")

old_home = """<div class="runtime-note"><strong>Modèle de travail Android.</strong> La gestion locale et la navigation sont fonctionnelles. Le runtime U-002 validé est conservé séparément et accessible par le bouton « Runtime Android ». Les formulaires Analyse / Fact Check ne prétendent pas encore transmettre leur texte au provider.</div>"""
new_home = """<div class="runtime-note"><strong>Modèle de travail Android.</strong> Le Workbench conserve localement les sujets et leurs fils. Le flux Analyse → ChatGPT → Result Pack → retour au fil est raccordé à un runtime dédié dérivé du transport U-002. Le bouton « Runtime Android » conserve l’accès au runtime U-002 de référence.</div>"""

old_analysis = """<section class="page" id="page-analysis"><div class="eyebrow">ANALYSE</div><h2>Analyse NEXUS</h2><div class="panel"><label>Question / demande</label><textarea id="analysisInput" placeholder="Saisissez la question à analyser…"></textarea><div class="actions"><button class="primary" onclick="prepareAnalysis()">Préparer & conserver</button><button class="ghost" onclick="openRuntime()">Ouvrir le runtime Android validé</button></div><div class="runtime-note">Le premier bouton crée réellement un tour local persistant. L’ouverture du runtime lance l’Activity U-002 finale existante ; l’injection automatique de cette question dans ce runtime sera un raccordement ultérieur.</div><div id="analysisResult" class="result empty">Aucun tour préparé.</div></div></section>"""
new_analysis = """<section class="page" id="page-analysis"><div class="eyebrow">ANALYSE</div><h2>Analyse NEXUS</h2><div class="panel"><label>Question / demande</label><textarea id="analysisInput" placeholder="Saisissez la question à analyser…"></textarea><div class="actions"><button class="primary" onclick="runAnalysisWithChatGPT()">Analyser avec ChatGPT</button><button class="ghost" onclick="prepareAnalysis()">Préparer seulement</button><button class="ghost" onclick="openRuntime()">Runtime U-002 de référence</button></div><div class="runtime-note">Le premier bouton crée le tour dans le sujet actif, transmet la question au runtime ChatGPT Android, attend un Result Pack corrélé puis revient automatiquement dans le fil du sujet. Aucun canonical write ni truth-winner n’est autorisé.</div><div id="analysisResult" class="result empty">Aucune analyse lancée.</div></div></section>"""

old_prepare = """function prepareAnalysis(){let q=document.getElementById('analysisInput').value.trim();if(!q){toast('Saisissez une question');return}let s=selectedSubject?db.subjects.find(x=>x.id===selectedSubject):ensureDefaultSubject();let id='AN-'+Date.now();let a={id,subjectId:s.id,provider:'WORKBENCH',prompt:q,response:'Préparé localement — en attente de raccordement au runtime provider.',updatedAt:now()};db.analyses.push(a);s.headAnalysisId=id;s.updatedAt=a.updatedAt;save();document.getElementById('analysisResult').className='result';document.getElementById('analysisResult').textContent='Tour local créé\\nanalysis_id : '+id+'\\nsubject_id : '+s.id+'\\n\\nLe contenu n’a pas été envoyé au provider.';toast('Analyse préparée et conservée')}"""

new_prepare = """function prepareAnalysis(){let q=document.getElementById('analysisInput').value.trim();if(!q){toast('Saisissez une question');return}let s=selectedSubject?db.subjects.find(x=>x.id===selectedSubject):ensureDefaultSubject();let id='AN-'+Date.now();let a={id,subjectId:s.id,provider:'WORKBENCH',status:'LOCAL_ONLY',prompt:q,response:'Préparé localement — non envoyé au provider.',updatedAt:now()};db.analyses.push(a);s.headAnalysisId=id;s.updatedAt=a.updatedAt;selectedSubject=s.id;save();document.getElementById('analysisResult').className='result';document.getElementById('analysisResult').textContent='Tour local créé\\nanalysis_id : '+id+'\\nsubject_id : '+s.id+'\\n\\nLe contenu n’a pas été envoyé au provider.';toast('Analyse préparée et conservée')}
function runAnalysisWithChatGPT(){let q=document.getElementById('analysisInput').value.trim();if(!q){toast('Saisissez une question');return}let s=selectedSubject?db.subjects.find(x=>x.id===selectedSubject):ensureDefaultSubject();let chain=analyses(s.id),previous=chain.length?chain[chain.length-1]:null;let id='AN-'+Date.now();let requestId='U011-'+id;let a={id,subjectId:s.id,provider:'CHATGPT',status:'RUNNING',prompt:q,response:'Exécution ChatGPT en cours…',updatedAt:now()};db.analyses.push(a);s.headAnalysisId=id;s.updatedAt=a.updatedAt;selectedSubject=s.id;save();document.getElementById('analysisResult').className='result';document.getElementById('analysisResult').textContent='Runtime ChatGPT en cours…\\nanalysis_id : '+id+'\\nsubject_id : '+s.id+'\\nrequest_id : '+requestId;let payload={request_id:requestId,analysis_id:id,subject_id:s.id,question:q,previous_context:previous?String(previous.response||'').slice(-12000):'',mode:'ANALYSIS'};try{if(window.NexusAndroid&&NexusAndroid.runAnalysis){NexusAndroid.runAnalysis(JSON.stringify(payload));return}}catch(e){runtimeAnalysisError(id,'ANDROID_BRIDGE_EXCEPTION:'+String(e))}runtimeAnalysisError(id,'ANDROID_RUNTIME_UNAVAILABLE')}
function runtimeAnalysisError(id,code){let a=db.analyses.find(x=>x.id===id);if(a){a.status='FAILED';a.response='Échec runtime : '+code;a.updatedAt=now();save()}showPage('analysis');let box=document.getElementById('analysisResult');box.className='result';box.textContent='Échec runtime\\n'+code;toast('Échec du runtime ChatGPT')}
function onRuntimeResult(raw){let r;try{r=typeof raw==='string'?JSON.parse(raw):raw}catch(e){toast('Result Pack Android illisible');return}let a=db.analyses.find(x=>x.id===r.analysis_id);if(!a){toast('Analyse locale introuvable');return}a.status=r.status||'COMPLETED';a.response=r.answer||'';a.provider='ChatGPT';a.modelRef=r.model_ref||'';a.contextPackId=r.context_pack_id||'';a.frozenFingerprint=r.frozen_fingerprint||'';a.terminalReceipt=r.terminal_receipt||'';a.updatedAt=now();let subj=db.subjects.find(x=>x.id===a.subjectId);if(subj){subj.headAnalysisId=a.id;subj.updatedAt=a.updatedAt;selectedSubject=subj.id;selectedTh=subj.theatreId}save();document.getElementById('analysisResult').className='result';document.getElementById('analysisResult').textContent='TERMINAL RECEIPT '+(r.terminal_receipt||'PASS')+'\\n'+(r.answer||'');toast('Résultat ChatGPT reçu');openThread(a.subjectId)}
window.NexusWorkbench={onRuntimeResult:onRuntimeResult,onRuntimeError:function(raw){let r;try{r=typeof raw==='string'?JSON.parse(raw):raw}catch(e){r={analysis_id:'',error:'ANDROID_RUNTIME_ERROR'}}runtimeAnalysisError(r.analysis_id||'',r.error||'ANDROID_RUNTIME_ERROR')}};"""

pairs = [(old_home,new_home),(old_analysis,new_analysis),(old_prepare,new_prepare)]
for old,new in pairs:
    if old not in s:
        raise SystemExit("WORKBENCH_PATCH_SOURCE_NOT_FOUND")
    s = s.replace(old,new,1)

s = s.replace(
    "document.getElementById('platformStatus').innerHTML=NexusAndroid.getPlatform()+' · Workbench local<br>Runtime U-002 final conservé'",
    "document.getElementById('platformStatus').innerHTML=NexusAndroid.getPlatform()+' · Workbench 002<br>Analyse ChatGPT raccordée · Runtime U-002 conservé'"
)
s = s.replace("NEXUS Workbench U-011", "NEXUS Workbench U-011 002")

path.write_text(s, encoding="utf-8")
