#!/usr/bin/env bash
set -euo pipefail
ROOT="$1"
PASS=0
FAIL=0
check(){ local name="$1"; shift; if "$@"; then echo "PASS $name"; PASS=$((PASS+1)); else echo "FAIL $name"; FAIL=$((FAIL+1)); fi; }
BG="$ROOT/app/build.gradle.kts"
MAN="$ROOT/app/src/main/AndroidManifest.xml"
MAIN="$ROOT/app/src/main/java/nexus/android/c002/MainActivity.kt"
LAY="$ROOT/app/src/main/res/layout/activity_main.xml"
CHAT="$ROOT/app/src/main/assets/nexus/chatgpt_provider_c002.js"
ORIGIN="$ROOT/app/src/main/java/nexus/android/c002/web/OriginPolicy.kt"

check app_id grep -Fq 'applicationId = "nexus.android.u004.uxshell002"' "$BG"
check version grep -Fq 'versionName = "0.0.41-u004-android-ux-shell002-autoclose"' "$BG"
check label grep -Fq 'android:label="NEXUS"' "$MAN"
check unique_profile grep -Fq 'nexus_provider_profile_u004_android_ux_shell_002' "$MAIN"
check u004_job grep -Fq 'U004-ANDROID-UX-SHELL-002-JOB-001' "$MAIN"
check u004_pack grep -Fq 'U004_ANDROID_UX_SHELL_002_V1' "$MAIN"
check u004_token grep -Fq 'NEXUS_U004_ANDROID_UX_SHELL_002_OK' "$MAIN"
check nexus_title grep -Fq 'android:id="@+id/nexusTitle"' "$LAY"
check nexus_brand grep -Fq 'android:text="NEXUS"' "$LAY"
check provider_badge grep -Fq 'android:id="@+id/providerBadge"' "$LAY"
check provider_visible grep -Fq 'android:text="ChatGPT"' "$LAY"
check nexus_menu grep -Fq 'android:id="@+id/nexusMenu"' "$LAY"
check popup_menu grep -Fq 'PopupMenu(this, anchorView)' "$MAIN"
check friendly_auth grep -Fq 'Connexion à ChatGPT requise' "$MAIN"
check friendly_running grep -Fq 'Analyse en cours…' "$MAIN"
check friendly_pass grep -Fq 'Terminé · résultat validé' "$MAIN"
check friendly_block grep -Fq 'Exécution bloquée · vérification de sécurité' "$MAIN"
check raw_details_on_demand grep -Fq 'append("\\n").append(currentHeadline)' "$MAIN"
check authfix2_probe grep -Fq "mode:'AUTO_AUTH_MENU_PROBE'" "$CHAT"
check menu_click_not_auth_proof grep -Fq 'menu_click_is_auth_proof:false' "$CHAT"
check autoclose_function grep -Fq 'function findAuthMenuCloseButton()' "$CHAT"
check autoclose_after_auth grep -Fq "if(status.state!=='AUTHENTICATED') return;" "$CHAT"
check autoclose_only_nexus_opened grep -Fq 'if(!authProbeOpenedSidebar) return;' "$CHAT"
check autoclose_marker grep -Fq "authProbeCloseLast='CLOSED_AFTER_AUTH_PROOF'" "$CHAT"
check autoclose_not_auth_proof grep -Fq 'sidebar_close_is_auth_proof:false' "$CHAT"
check close_selector_en grep -Fq 'button[aria-label="Close sidebar"]' "$CHAT"
check close_selector_fr grep -Fq 'button[aria-label="Fermer la barre latérale"]' "$CHAT"
check exact_chatgpt_origin grep -Fq 'const val CHATGPT_ORIGIN = "https://chatgpt.com"' "$MAIN"
check auth_google_exact grep -Fq 'host == "accounts.google.com"' "$ORIGIN"
check terminal_receipt grep -Fq 'TERMINAL_RECEIPT_PASS' "$MAIN"
check external_research_false grep -Fq '.put("external_research", false)' "$MAIN"
check canonical_write_false grep -Fq '.put("canonical_write", false)' "$MAIN"
check state_mutation_none grep -Fq '.put("state_mutation_mode", "NONE")' "$MAIN"
check truth_winner_none grep -Fq '.put("truth_winner", "NONE")' "$MAIN"
check no_webview_debug bash -c "! grep -Fq 'setWebContentsDebuggingEnabled(true)' '$MAIN'"
check node_syntax node --check "$CHAT"
check no_add_javascript_interface bash -c "! grep -R -Fq --include='*.kt' --include='*.java' --include='*.js' 'addJavascriptInterface' '$ROOT/app/src/main'"

echo "U004_UX_SHELL_002_STATIC_RESULT pass=$PASS fail=$FAIL"
test "$FAIL" -eq 0
