#!/usr/bin/env bash
set -euo pipefail
ROOT="${1:?root required}"
REF="${2:?023 reference required}"
pass=0; fail=0
check(){ local n="$1"; shift; if "$@"; then echo "PASS $n"; pass=$((pass+1)); else echo "FAIL $n"; fail=$((fail+1)); fi; }
MAIN="$ROOT/app/src/main/java/nexus/android/c002/MainActivity.kt"
GRADLE="$ROOT/app/build.gradle.kts"; MANIFEST="$ROOT/app/src/main/AndroidManifest.xml"; LAYOUT="$ROOT/app/src/main/res/layout/activity_main.xml"
CLAUDE="$ROOT/app/src/main/assets/nexus/claude_provider_c002.js"; CHATGPT="$ROOT/app/src/main/assets/nexus/chatgpt_provider_c002.js"
ORIGIN="$ROOT/app/src/main/java/nexus/android/c002/web/OriginPolicy.kt"; BRIDGE="$ROOT/app/src/main/java/nexus/android/c002/web/NexusWebBridge.kt"
check application_id_024 grep -Fq 'applicationId = "nexus.android.c002.durablerunownership024"' "$GRADLE"
check version_024 grep -Fq 'versionCode = 25' "$GRADLE"
check version_name_024 grep -Fq '0.0.25-c002-durable-run-ownership024' "$GRADLE"
check label_024 grep -Fq 'NEXUS C002 DURABLE RUN OWNERSHIP 024' "$MANIFEST"
check evidence_024 grep -Fq 'EVIDENCE 024 | BOOT=' "$MAIN"
check panel_7_lines grep -Fq 'android:maxLines="7"' "$LAYOUT"
check boot_decision_field grep -Fq 'bootDecision = BOOT_DECISION_INITIALIZING' "$MAIN"
check prior_state_snapshot grep -Fq 'RUN_BOOT_PRIOR_STATE_KEY' "$MAIN"
check prior_age_snapshot grep -Fq 'RUN_BOOT_PRIOR_AGE_MS_KEY' "$MAIN"
check prior_run_snapshot grep -Fq 'RUN_BOOT_PRIOR_RUN_ID_KEY' "$MAIN"
check prior_phase_snapshot grep -Fq 'RUN_BOOT_PRIOR_PHASE_KEY' "$MAIN"
check boot_commit grep -Fq '.putLong(RUN_BOOT_AT_MS_KEY, bootNow).commit()' "$MAIN"
check explicit_resume_decision grep -Fq 'BOOT_DECISION_RESUME -> resumeExecutionProof(origin)' "$MAIN"
check explicit_fresh_decision grep -Fq 'BOOT_DECISION_FRESH -> startExecutionProof(origin)' "$MAIN"
check no_implicit_dispatch grep -Fq 'ANDROID_BOOT_DECISION_NOT_ESTABLISHED' "$MAIN"
check fresh_owner_commit grep -Fq 'private fun armRunLatch(job: ExecutionJob): Boolean' "$MAIN"
check execute_post_commit grep -Fq 'durable_commit=true' "$MAIN"
check resume_state_commit grep -Fq 'val resumeStateCommitted = runLatch.edit()' "$MAIN"
check resume_job_024 grep -Fq 'recordDiagnostic("RESUME_JOB_024"' "$MAIN"
check recoverable_boolean grep -Fq 'private fun markRunRecoverable(code: String): Boolean' "$MAIN"
check recoverable_commit grep -Fq 'RUN_STATE_RECOVERABLE' "$MAIN"
check recoverable_commit_fail_closed grep -Fq 'ANDROID_RUN_STATE_COMMIT_FAILED_RECOVERABLE' "$MAIN"
check prompt_counter_commit grep -Fq 'RUN_EVIDENCE_PROMPT_INJECTION_COUNT_KEY, 1).commit()' "$MAIN"
check send_counter_commit grep -Fq 'RUN_EVIDENCE_SEND_CLICK_COUNT_KEY, next).commit()' "$MAIN"
check fresh_block_on_stale grep -Fq 'BOOT_DECISION_BLOCK_STALE' "$MAIN"
check fresh_block_on_metadata grep -Fq 'BOOT_DECISION_BLOCK_METADATA' "$MAIN"
check prefs_024 grep -Fq 'nexus_v005_durable_run_ownership_024' "$MAIN"
check stable_webview_profile grep -Fq 'nexus_provider_profile_c002_rotationrunstate019' "$MAIN"
check claude_identical cmp -s "$CLAUDE" "$REF/app/src/main/assets/nexus/claude_provider_c002.js"
check chatgpt_identical cmp -s "$CHATGPT" "$REF/app/src/main/assets/nexus/chatgpt_provider_c002.js"
check origin_identical cmp -s "$ORIGIN" "$REF/app/src/main/java/nexus/android/c002/web/OriginPolicy.kt"
check bridge_identical cmp -s "$BRIDGE" "$REF/app/src/main/java/nexus/android/c002/web/NexusWebBridge.kt"
check no_prompt_persisted bash -c "! grep -q 'RUN_LATCH_QUESTION\|PROOF_QUESTION.*putString\|PROOF_HANDOFF.*putString' '$MAIN'"
check no_cookie_persisted bash -c "! grep -qi 'putString.*cookie' '$MAIN'"
check claude_js_syntax node --check "$CLAUDE"
echo "DURABLE_RUN_OWNERSHIP_024_STATIC_RESULT pass=$pass fail=$fail"
test "$fail" -eq 0
